name = "sleepzzz"
main = "src/index.js"
compatibility_date = "2024-12-01"

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "sleepzzz-db"
database_id = "29b3ce07-4e06-4a11-aa7f-d59f19b48db5"
